# Generated by Django 5.2.6 on 2025-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('file', models.FileField(upload_to='resume/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tools',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='certification',
            name='license_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
