# Generated by Django 5.2.6 on 2025-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resume_projects_tools_alter_certification_license_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tools',
        ),
        migrations.AddField(
            model_name='projects',
            name='tools',
            field=models.ManyToManyField(blank=True, to='main.tool'),
        ),
    ]
