# Generated by Django 5.2.6 on 2025-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_link_contactdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='resume',
        ),
        migrations.AddField(
            model_name='projects',
            name='demo_video',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_repo',
            field=models.URLField(blank=True, help_text='Optional GitHub repo link', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='readme_file',
            field=models.FileField(blank=True, null=True, upload_to='project_readmes/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, help_text='Project live demo / GitHub link'),
        ),
    ]
