# Generated by Django 5.2.6 on 2025-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='explanation',
            field=models.TextField(blank=True, help_text='Short explanation or details about this screenshot.', null=True),
        ),
    ]
