# Generated by Django 5.2.6 on 2025-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_screenshot_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, help_text='Project live demo'),
        ),
    ]
