# Generated by Django 5.2.6 on 2025-09-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, help_text='Project live demo / GitHub link'),
        ),
    ]
